[project]
name = "threads-likes"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "must1d"},
]
dependencies = ["selenium>=4.26.1"]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
